### ISSUE TITLE
Seeking guidance to perform Semantic Segmentation of Point Cloud Data

### ISSUE THREAD

**Issue by sai1992c** [lilanxiao/image2point#1]
I really appreciate your efforts for this work. And I'm very much eager to try out Semantic Segmentation of point cloud data for my custom dataset. Hence seeking your valuable guidance and help

I have a dataset - a lot of text files each containing X, Y, Z and C (Classification) values per each line
This dataset is obtained from https://environment.data.gov.uk/defradatadownload/?mode=survey

Since I'm very new to this domain. I seek your help on how to preprocess the above text files into train and test folders
and whether your implementation can be used for Semantic Segmentation?

Your guidance will be very helpful for me and would be grateful for the same.

Thanks in advance

**Comment by lilanxiao** [comment]
To load text file, [numpy.loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) can be useful. For preprocessing, the easiest way is probably using [Open3D](http://www.open3d.org/). Please read the documentation of these libraries for more information. 

Yes, my code can be used for segmentation tasks. Simply add some upsampling layers to sparse ResNets, that's it. If you are not familiar with MinkowskiEngine, [here](https://github.com/NVIDIA/MinkowskiEngine/tree/master/examples) are some examples.

**Comment by sai1992c** [comment]
@lilanxiao Thanks a lot for quick response. Let me try it..!
